const cars = [
  {
    image: "./assets/suv.png",
    name: "Volvo XC90",
    type: "SUV",
    category: "Standard",
    persons: 5,
    suitcases: 4,
    price: 867,
  },
  {
    image: "./assets/hatchback.png",
    name: "Hiyundai i30",
    type: "Hatchpack",
    category: "Standard",
    persons: 4,
    suitcases: 3,
    price: 623,
  },
  {
    image: "./assets/sport.png",
    name: "Chevrollet UltraSport",
    type: "Sport",
    category: "Standard",
    persons: 4,
    suitcases: 3,
    price: 1500,
  },
  {
    image: "./assets/van.webp",
    name: "Chevrolet Van",
    type: "Van",
    category: "Van",
    persons: 9,
    suitcases: 6,
    price: 1800,
  },
  {
    image: "./assets/limo.png",
    name: "Mercedes-Benz",
    type: "Limousine",
    category: "Limousine",
    persons: 9,
    suitcases: 5,
    price: 2180,
  },
];
